title: "CobiontID"
remote-theme: chrisrhymes/bulma-clean-theme@master
baseurl: "/"

plugins:
- github-pages
- jekyll-remote-theme

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      menubar: docs_menu
      hero_height: small
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_sidebar: false
      menubar: docs_menu
