title: "CobiontID"
remote-theme: chrisrhymes/bulma-clean-theme


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      menubar: docs_menu
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_sidebar: false
      menubar: docs_menu
