title: "CobiontID"
remote-theme: chrisrhymes/bulma-clean-theme
baseurl: ""

plugins:
- github-pages
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed
- jekyll-seo-tag
- kramdown-parser-gfm
- jekyll-redirect-from


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      menubar: docs_menu
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_sidebar: false
      menubar: docs_menu
